---
http_interactions:
- request:
    method: get
    uri: https://api.trello.com/1/boards/50ce927d006f9d1b63010458
    body:
      encoding: US-ASCII
      string: ''
    headers:
      accept:
      - ! '*/*; q=0.5, application/xml'
      accept-encoding:
      - gzip, deflate
      authorization:
      - OAuth oauth_consumer_key="5bc3bf6f350105ad4a099b9c115bb058", oauth_nonce="4471022be4303ebbaece20a60e5452f5",
        oauth_signature="p6JGLNXEQpg%2B9mXIqHGcoNqe3wk%3D", oauth_signature_method="HMAC-SHA1",
        oauth_timestamp="1357819747", oauth_version="1.0"
      user-agent:
      - Ruby
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      x-powered-by:
      - Express
      content-type:
      - text/plain; charset=utf-8
      content-length:
      - '34'
      cache-control:
      - max-age=0, must-revalidate, no-cache, no-store
      expires:
      - Thu, 01 Jan 1970 00:00:00
      access-control-allow-origin:
      - ! '*'
      access-control-allow-methods:
      - GET, PUT, POST, DELETE
      set-cookie:
      - connect.sid=apPVZePce7xkwCfbPv81r4KZ.ux4tSatASZIk9%2Bg96fYtnsEpVXP%2F4GdJkjc5CBHJpEA;
        path=/; httpOnly
      date:
      - Thu, 10 Jan 2013 12:09:06 GMT
      connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ! 'unauthorized permission requested

'
    http_version: '1.1'
  recorded_at: Thu, 10 Jan 2013 12:09:07 GMT
recorded_with: VCR 2.3.0
