development:
  adapter: postgresql
  encoding: unicode
  database: bottleneck_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bottleneck_test
  pool: 5
  username:
  password:
